# Generated by Django 4.2.5 on 2023-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_companions_ticket_date_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='companions',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='companions',
            field=models.ManyToManyField(blank=True, to='tickets.ticket'),
        ),
    ]
