# Generated by Django 4.2.5 on 2023-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_name_ticket_titular_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='companions',
        ),
        migrations.AddField(
            model_name='ticket',
            name='companions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
