# Generated by Django 4.2.5 on 2023-09-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_companions_ticket_companions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='companions',
        ),
    ]
