# Generated by Django 4.2.5 on 2023-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
