# Generated by Django 4.2.5 on 2023-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_person_time_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time_checked',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
